version: '3.8'
services:
  api:
    build:
      context: ./api/
    image: pichapterapi:production
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    ports:
      - "8080:8080"
    # env_file: ./api/.env # TODO - uncomment this to auto-load your .env file!
    container_name: production_api
    restart: always
    networks:
      - backend
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    image: pichapterclient:production
    # command: npm start
    depends_on:
      - api
    ports:
      - "80:80"
    container_name: production_client
    restart: always
    networks:
      - backend
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: zach
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: piChapter
    volumes:
      - './db/schema:/docker-entrypoint-initdb.d'
      - './db/data:/var/lib/mysql'
      - './db/setup:/var/lib/mysql-files/'
    container_name: production_db
    networks:
      - backend
networks:
  backend:
