apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    app: mysql-db
  clusterIP: None
  ports:
  - port: 3306
    name: db-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: db-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:8.0.24
          name: mysql-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: piChapter
            - name: MYSQL_USER
              value: zach
            - name: MYSQL_PASSWORD
              value: toor
          ports:
            - containerPort: 3306
              name: mysql-db
          volumeMounts:
            - name: db-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Mi