apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /home/zach/Desktop/db-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  resources:
    requests:
      storage: 5G
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    app: mysql-db
  type: NodePort
  ports:
  - port: 3306
    name: db-port
    nodePort: 30336
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-db
spec:
  selector:
    matchLabels:
      app: mysql-db
  serviceName: db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: pi-db:1.0.0
          name: mysql-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: piChapter
            - name: MYSQL_USER
              value: zach
            - name: MYSQL_PASSWORD
              value: toor
          # ports:
          #   - containerPort: 3306
          #     name: mysql-db
          volumeMounts:
            - name: db-pvc
              mountPath: /var/lib/mysql
      volumes:
      - name: db-pvc
        persistentVolumeClaim:
          claimName: db-pvc