apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pichapter-ingress
spec:
  rules:
  - host: key.test.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-svc
            port: 
              number: 80
  # - host: key.test.org
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/"
  #       backend:
  #         service:
  #           name: keycloak
  #           port: 
  #             number: 80
