spring:
  main:
    banner-mode: off
  application:
    name: chapter
  datasource:
#    url: jdbc:mysql://db.kube.cloudapps.ms3-inc.com:30001/MS3BusinessContacts
    url: jdbc:mysql://localhost:3306/piChapter
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      maxLifetime: 180000
#      minimumIdle: 3
#      maximumPoolSize: 10

camel:
  springboot:
    name: chapter
    use-mdc-logging: true
  rest:
    port: 9000
    context-path: /api/pi
#management:
#  endpoint:
#    camelroutes:
#      enabled: true
#      read-only: true
#    health:
#      enabled: true
#      probes:
#        enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: info,health,camelroutes,metrics
#  health:
#    livenessstate:
#      enabled: true
#    readinessstate:
#      enabled: true